// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu6GzieN6kzaBbttRJSTLi0n05pfwaCYA',
    appId: '1:195818647694:web:d1a5cad47f29da0184d9df',
    messagingSenderId: '195818647694',
    projectId: 'chat-app-dd115',
    authDomain: 'chat-app-dd115.firebaseapp.com',
    storageBucket: 'chat-app-dd115.firebasestorage.app',
    measurementId: 'G-FECBXVW9S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO2w6_BbrKLA9T-DE252-HIdwKnJEfH1I',
    appId: '1:195818647694:android:81a7c03f849fe86284d9df',
    messagingSenderId: '195818647694',
    projectId: 'chat-app-dd115',
    storageBucket: 'chat-app-dd115.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYcWLrQyU92maJcZIFKRWJTBKOWSe2DMw',
    appId: '1:195818647694:ios:3cd202da707e58fb84d9df',
    messagingSenderId: '195818647694',
    projectId: 'chat-app-dd115',
    storageBucket: 'chat-app-dd115.firebasestorage.app',
    iosBundleId: 'com.example.scolar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYcWLrQyU92maJcZIFKRWJTBKOWSe2DMw',
    appId: '1:195818647694:ios:3cd202da707e58fb84d9df',
    messagingSenderId: '195818647694',
    projectId: 'chat-app-dd115',
    storageBucket: 'chat-app-dd115.firebasestorage.app',
    iosBundleId: 'com.example.scolar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu6GzieN6kzaBbttRJSTLi0n05pfwaCYA',
    appId: '1:195818647694:web:8e415b05f6e6c50484d9df',
    messagingSenderId: '195818647694',
    projectId: 'chat-app-dd115',
    authDomain: 'chat-app-dd115.firebaseapp.com',
    storageBucket: 'chat-app-dd115.firebasestorage.app',
    measurementId: 'G-90VC3N8YD9',
  );
}
